import type { Brand, BrandId } from './types';

/* ==========================================================================
   Three worked examples. Swap these objects for API responses and the whole
   product — site, widget, console — re-skins and re-behaves.
   ========================================================================== */

export const PRODUCT = {
  name: 'Saint',
  line: 'The assistant that books, sells and answers.',
};

const lumiere: Brand = {
  id: 'lumiere',
  vertical: 'restaurant',
  name: 'Lumière',
  legal: 'Lumière Restaurant',
  kind: 'Restaurant · Marylebone',
  scheme: 'dark',
  currency: '£',
  address: '9 Weymouth Mews, Marylebone',
  district: 'London W1G',
  phone: '+44 20 7946 0221',

  hero: {
    eyebrow: 'Small plates · natural wine · open until late',
    line1: 'Dinner, and',
    line2: 'everything after.',
    body: 'A twelve-table room off Weymouth Mews. Order in for tonight, or take a table and let us feed you properly.',
    cta: 'Order for tonight',
    stats: [
      { value: '25', label: 'Minute delivery' },
      { value: '4.8', label: 'From 1,240 reviews' },
      { value: '12', label: 'Tables only' },
    ],
  },
  nav: ['Menu', 'Wine list', 'Private dining', 'Find us'],

  images: {
    hero: 'photo-1517248135467-4c7edcad34c4',
    feature: [
      'photo-1621494268492-d01b98eba7e4',
      'photo-1414235077428-338989a2e8c0',
      'photo-1566670829023-5badae05aa7d',
    ],
    story: 'photo-1552566626-52f8b828add9',
  },
  story: {
    eyebrow: 'The room',
    title: 'Twelve tables, one fire, no reservations after ten.',
    body: 'We cook over coals and open bottles nobody else is pouring. The counter seats eight and is kept back for whoever walks in.',
    points: [
      'Everything on the menu goes out of the same open kitchen',
      'Wine is low intervention, mostly French, always cold',
      'Delivery inside three miles, twenty-five minutes',
    ],
  },
  marquee: ['Small plates', 'Natural wine', 'Open until late', 'Walk-ins welcome', 'Marylebone'],
  process: [
    { title: 'Order or reserve', note: 'Tell Saint what you want and when. No app, no account.' },
    { title: 'The kitchen picks it up', note: 'Tickets land on the pass the moment they are confirmed.' },
    { title: 'Cooked to order', note: 'Nothing sits. Small batches through the whole service.' },
    { title: 'At your door', note: 'Three miles, twenty-five minutes, tracked the whole way.' },
  ],
  proof: [
    { value: '1,240+', label: 'Reviews' },
    { value: '12', label: 'Tables' },
  ],

  assistant: {
    greeting: "Evening — I'm Saint, the front of house for Lumière.",
    offer: 'I can take an order, hold you a table, or tell you what the kitchen is doing well tonight.',
    nudgeTitle: 'Hungry?',
    nudgeBody: 'Kitchen is open for another two hours. I can have this at your door in twenty-five minutes.',
    human: 'Odile Renard',
    humanRole: 'Restaurant manager',
  },

  skills: { order: true, reserve: true, appointment: false },
  itemNoun: 'dish',
  itemNounPlural: 'dishes',
  tagNoun: 'Allergens',
  peopleNoun: 'team',

  categories: [
    { id: 'small', name: 'Small plates', note: 'Two or three each to start' },
    { id: 'large', name: 'Large plates', note: 'One each, served to share' },
    { id: 'sweet', name: 'Sweet', note: 'The kitchen insists' },
    { id: 'wine', name: 'Wine', note: 'Low intervention, mostly French' },
  ],

  catalog: [
    {
      id: 'l1',
      name: 'Sourdough & cultured butter',
      categoryId: 'small',
      price: 6,
      description:
        'Four-day starter, baked twice a day. Butter churned in-house and salted with Maldon.',
      tags: ['Gluten', 'Dairy'],
      available: true,
      hue: 38,
      popular: true,
      sold: 412,
    },
    {
      id: 'l2',
      name: 'Devon crab, brown butter, chilli',
      categoryId: 'small',
      price: 16,
      description:
        'Hand-picked white meat, warm brown butter, a little chilli and lemon. Toast on the side.',
      tags: ['Crustacean', 'Dairy', 'Gluten'],
      available: true,
      hue: 18,
      popular: true,
      sold: 288,
    },
    {
      id: 'l3',
      name: 'Burrata, grilled peach, basil oil',
      categoryId: 'small',
      price: 14,
      description: 'Puglian burrata at room temperature, peaches off the grill, basil oil.',
      tags: ['Dairy'],
      available: true,
      hue: 52,
      sold: 196,
    },
    {
      id: 'l4',
      name: 'Beef tartare, smoked egg yolk',
      categoryId: 'small',
      price: 15,
      description: 'Hand-cut sirloin, capers, shallot, cured and smoked yolk grated over.',
      tags: ['Egg', 'Raw'],
      available: false,
      hue: 8,
      sold: 174,
    },
    {
      id: 'l5',
      name: 'Cornish turbot, seaweed butter',
      categoryId: 'large',
      price: 34,
      description:
        'On the bone over coals, basted in seaweed butter. Enough for two if you order well.',
      tags: ['Fish', 'Dairy'],
      available: true,
      hue: 190,
      popular: true,
      sold: 231,
    },
    {
      id: 'l6',
      name: 'Dry-aged rib, bone marrow',
      categoryId: 'large',
      price: 42,
      description: '55-day aged rib for two, roast bone marrow, watercress and a green sauce.',
      tags: ['Dairy'],
      available: true,
      hue: 0,
      sold: 208,
    },
    {
      id: 'l7',
      name: 'Girolles, egg yolk, aged comté',
      categoryId: 'large',
      price: 24,
      description: 'Girolles in butter and thyme, a raw yolk stirred through, comté grated late.',
      tags: ['Dairy', 'Egg'],
      available: true,
      hue: 44,
      sold: 143,
    },
    {
      id: 'l8',
      name: 'Salt-baked celeriac, hazelnut',
      categoryId: 'large',
      price: 21,
      description: 'Whole celeriac baked in salt for three hours, brown butter, toasted hazelnut.',
      tags: ['Nuts', 'Dairy', 'Vegetarian'],
      available: true,
      hue: 30,
      sold: 97,
    },
    {
      id: 'l9',
      name: 'Basque cheesecake',
      categoryId: 'sweet',
      price: 9,
      description: 'Burnt on top, barely set in the middle. The one thing nobody shares.',
      tags: ['Dairy', 'Egg', 'Gluten'],
      available: true,
      hue: 34,
      popular: true,
      sold: 356,
    },
    {
      id: 'l10',
      name: 'Chocolate & olive oil, sea salt',
      categoryId: 'sweet',
      price: 10,
      description: '70% Valrhona, Arbequina oil, flaked salt. Served cold.',
      tags: ['Dairy'],
      available: true,
      hue: 22,
      sold: 164,
    },
    {
      id: 'l11',
      name: 'Domaine Léonine, Roussillon',
      categoryId: 'wine',
      price: 46,
      description: 'Carignan, whole bunch, zero sulphur. Cold, and a little wild.',
      tags: ['Sulphites'],
      available: true,
      hue: 340,
      sold: 189,
    },
    {
      id: 'l12',
      name: 'Les Lunes Chenin, Loire',
      categoryId: 'wine',
      price: 38,
      description: 'Skin contact for four days. Quince, chamomile, a saline finish.',
      tags: ['Sulphites'],
      available: true,
      hue: 46,
      sold: 152,
    },
  ],

  people: [],

  hours: [
    { day: 'Tuesday – Thursday', hours: '17:30 – 23:00' },
    { day: 'Friday – Saturday', hours: '12:00 – 00:30' },
    { day: 'Sunday', hours: '12:00 – 17:00' },
    { day: 'Monday', hours: 'Closed' },
  ],

  faq: [
    {
      id: 'f1',
      q: 'Do you take walk-ins?',
      a: 'Always — the eight seats at the counter are held back for walk-ins every service. Tables are worth booking.',
      source: 'Booking policy',
      category: 'Reservations',
      uses: 214,
      confidence: 97,
      updated: '2 days ago',
      status: 'live',
    },
    {
      id: 'f2',
      q: 'How far do you deliver?',
      a: 'Three miles from W1G, which covers most of Marylebone, Fitzrovia, Soho and Mayfair. Twenty-five minutes on average.',
      source: 'Delivery zones',
      category: 'Delivery',
      uses: 189,
      confidence: 99,
      updated: 'Yesterday',
      status: 'live',
    },
    {
      id: 'f3',
      q: 'Can you cater for allergies?',
      a: 'Yes. Every dish is tagged, and the kitchen adjusts most plates. Tell me the allergy and I will flag it on the order.',
      source: 'Allergen handling',
      category: 'Kitchen',
      uses: 147,
      confidence: 94,
      updated: '5 days ago',
      status: 'live',
    },
    {
      id: 'f4',
      q: 'Is there a corkage fee?',
      a: '£25 a bottle, waived on Tuesdays. Two bottles per table maximum.',
      source: 'Wine policy',
      category: 'Wine',
      uses: 76,
      confidence: 92,
      updated: '3 weeks ago',
      status: 'live',
    },
    {
      id: 'f5',
      q: 'Do you do private hire?',
      a: 'The whole room seats 34, or 46 standing. Minimum spend from £3,200 depending on the night.',
      source: 'Private dining',
      category: 'Events',
      uses: 52,
      confidence: 88,
      updated: '1 month ago',
      status: 'review',
    },
    {
      id: 'f6',
      q: 'Is there parking nearby?',
      a: 'Q-Park Harley Street is a four-minute walk. Meters on Weymouth Mews are free after 18:30.',
      source: 'Finding us',
      category: 'Visiting',
      uses: 41,
      confidence: 84,
      updated: '2 months ago',
      status: 'draft',
    },
  ],
};

const aurelia: Brand = {
  id: 'aurelia',
  vertical: 'clinic',
  name: 'Aurelia',
  legal: 'Aurelia Clinic',
  kind: 'Private clinic · Chelsea',
  scheme: 'light',
  currency: '£',
  address: '18 Marlowe Street, Chelsea',
  district: 'London SW3',
  phone: '+44 20 7946 0812',

  hero: {
    eyebrow: 'Private clinic · Chelsea, London',
    line1: 'Considered care,',
    line2: 'unhurried.',
    body: 'Forty-minute appointments as standard, four specialists under one roof, and someone who answers at two in the morning — because that is often when you need it.',
    cta: 'Find an appointment',
    stats: [
      { value: '4.9', label: 'Patient rating' },
      { value: '40', label: 'Minute visits' },
      { value: '24/7', label: 'Booking line' },
    ],
  },
  nav: ['Treatments', 'Our team', 'Visiting', 'Journal'],

  images: {
    hero: 'photo-1512290923902-8a9f81dc236c',
    feature: [
      'photo-1489278353717-f64c6ee8a4d2',
      'photo-1583416750470-965b2707b355',
      'photo-1540555700478-4be289fbecef',
    ],
    story: 'photo-1583416750470-965b2707b355',
  },
  story: {
    eyebrow: 'How we work',
    title: 'Forty minutes, because ten was never enough.',
    body: 'Four specialists, one building, and notes that follow you between them. You leave with a written plan rather than a leaflet.',
    points: [
      'Same-week appointments, most weeks same-day',
      'Direct billing with Bupa, AXA, Vitality and Aviva',
      'Step-free throughout, with blue-badge bays outside',
    ],
  },
  marquee: ['General medicine', 'Dermatology', 'Dental', 'Physiotherapy', 'Chelsea'],
  process: [
    { title: 'Private consultation', note: 'History, examination and goals reviewed. No obligation.' },
    { title: 'A written plan', note: 'What we recommend, what it costs, and what it will not fix.' },
    { title: 'Your appointment', note: 'Forty minutes as standard, with the clinician you chose.' },
    { title: 'Follow-up', note: 'A review within fourteen days, included in the fee.' },
  ],
  proof: [
    { value: '2,400+', label: 'Appointments' },
    { value: '14 yrs', label: 'Experience' },
  ],

  assistant: {
    greeting: "Good day — I'm Saint, the concierge for Aurelia Clinic.",
    offer: 'I can book you in, move an appointment, or answer anything about the clinic.',
    nudgeTitle: 'Need a slot this week?',
    nudgeBody: 'I can check the diary and book you in — it takes about thirty seconds.',
    human: 'Marguerite Vance',
    humanRole: 'Patient coordinator',
  },

  skills: { order: false, reserve: false, appointment: true },
  itemNoun: 'treatment',
  itemNounPlural: 'treatments',
  tagNoun: 'Includes',
  peopleNoun: 'clinicians',

  categories: [
    { id: 'general', name: 'General medicine', note: 'Whole-picture consultations' },
    { id: 'derm', name: 'Dermatology', note: 'Skin, hair and nails' },
    { id: 'dental', name: 'Dental', note: 'Hygiene and restorative' },
    { id: 'physio', name: 'Physiotherapy', note: 'Movement and recovery' },
  ],

  catalog: [
    {
      id: 'a1',
      name: 'General consultation',
      categoryId: 'general',
      price: 120,
      description:
        'A full forty minutes with one of our physicians, including examination and a written plan.',
      tags: ['Written plan', 'Referrals'],
      duration: '40 min',
      available: true,
      hue: 168,
      popular: true,
      sold: 186,
    },
    {
      id: 'a2',
      name: 'Annual health review',
      categoryId: 'general',
      price: 480,
      description: 'Bloods, ECG, lung function and a ninety-minute review of the results with you.',
      tags: ['Bloods', 'ECG', '90 min'],
      duration: '90 min',
      available: true,
      hue: 186,
      sold: 64,
    },
    {
      id: 'a3',
      name: 'Mole mapping & skin check',
      categoryId: 'derm',
      price: 180,
      description:
        'Full-body dermoscopy, photographed and compared against your previous visit.',
      tags: ['Photography', 'Report'],
      duration: '45 min',
      available: true,
      hue: 24,
      popular: true,
      sold: 142,
    },
    {
      id: 'a4',
      name: 'Acne & rosacea consultation',
      categoryId: 'derm',
      price: 165,
      description: 'Assessment, a prescription where appropriate, and a six-week follow-up included.',
      tags: ['Prescription', 'Follow-up'],
      duration: '40 min',
      available: true,
      hue: 8,
      sold: 98,
    },
    {
      id: 'a5',
      name: 'Hygiene & six-month check',
      categoryId: 'dental',
      price: 95,
      description: 'Scale, polish, and a full examination with small X-rays if they are due.',
      tags: ['X-rays', 'Polish'],
      duration: '40 min',
      available: true,
      hue: 200,
      sold: 224,
    },
    {
      id: 'a6',
      name: 'Composite bonding',
      categoryId: 'dental',
      price: 340,
      description: 'Per tooth, shade-matched and finished in a single visit.',
      tags: ['Single visit'],
      duration: '60 min',
      available: false,
      hue: 46,
      sold: 37,
    },
    {
      id: 'a7',
      name: 'Physiotherapy session',
      categoryId: 'physio',
      price: 110,
      description: 'Movement assessment, hands-on treatment, and exercises you will actually do.',
      tags: ['Hands-on', 'Home plan'],
      duration: '50 min',
      available: true,
      hue: 148,
      popular: true,
      sold: 176,
    },
    {
      id: 'a8',
      name: 'Running gait analysis',
      categoryId: 'physio',
      price: 145,
      description: 'Treadmill filming from four angles, with a written report and load plan.',
      tags: ['Video', 'Report'],
      duration: '60 min',
      available: true,
      hue: 210,
      sold: 52,
    },
  ],

  people: [
    {
      id: 'p1',
      name: 'Amara Okonjo',
      title: 'Dr',
      role: 'General medicine',
      focus: ['general', 'derm'],
      rating: 4.9,
      reviews: 218,
      next: 'Today, 15:30',
      hue: 168,
      bio: 'Fifteen years in general practice, with an interest in long-term fatigue.',
    },
    {
      id: 'p2',
      name: 'Levi Hartmann',
      title: 'Dr',
      role: 'Dermatology',
      focus: ['derm', 'general'],
      rating: 4.8,
      reviews: 164,
      next: 'Tomorrow, 09:00',
      hue: 24,
      bio: 'Consultant dermatologist, mole mapping and skin cancer surveillance.',
    },
    {
      id: 'p3',
      name: 'Noor Rahimi',
      title: 'Dr',
      role: 'Dental surgery',
      focus: ['dental'],
      rating: 5,
      reviews: 91,
      next: 'Today, 17:00',
      hue: 200,
      bio: 'Restorative and cosmetic dentistry, unhurried and unusually gentle.',
    },
    {
      id: 'p4',
      name: 'Sena Ellery',
      title: 'Ms',
      role: 'Physiotherapy',
      focus: ['physio'],
      rating: 4.9,
      reviews: 143,
      next: 'Thu, 11:15',
      hue: 148,
      bio: 'Musculoskeletal physiotherapist, works with three London running clubs.',
    },
  ],

  hours: [
    { day: 'Monday – Thursday', hours: '08:00 – 19:00' },
    { day: 'Friday', hours: '08:00 – 17:30' },
    { day: 'Saturday', hours: '09:00 – 14:00' },
    { day: 'Sunday', hours: 'Closed' },
  ],

  faq: [
    {
      id: 'f1',
      q: 'Which insurers do you accept?',
      a: 'We bill Bupa, AXA Health, Vitality and Aviva directly. Cigna and WPA we invoice, and you claim it back.',
      source: 'Insurance & billing',
      category: 'Billing',
      uses: 231,
      confidence: 98,
      updated: '4 days ago',
      status: 'live',
    },
    {
      id: 'f2',
      q: 'Do I need a referral?',
      a: 'Not for anything on our list. If your insurer needs one, your GP can send it straight to us.',
      source: 'Before your visit',
      category: 'Appointments',
      uses: 178,
      confidence: 96,
      updated: '1 week ago',
      status: 'live',
    },
    {
      id: 'f3',
      q: 'What is your cancellation policy?',
      a: 'Free up to 24 hours before. Inside 24 hours we charge half the fee, waived if you are unwell.',
      source: 'Cancellation policy',
      category: 'Policies',
      uses: 142,
      confidence: 99,
      updated: 'Yesterday',
      status: 'live',
    },
    {
      id: 'f4',
      q: 'Is the clinic step-free?',
      a: 'Yes. The Marlowe Street entrance is level, the lift reaches every floor, and blue-badge bays sit outside.',
      source: 'Access & parking',
      category: 'Visiting',
      uses: 97,
      confidence: 93,
      updated: '2 weeks ago',
      status: 'live',
    },
    {
      id: 'f5',
      q: 'Can I get a repeat prescription?',
      a: 'If we prescribed it in the last six months, yes — usually the same working day.',
      source: 'Prescriptions',
      category: 'Treatments',
      uses: 64,
      confidence: 74,
      updated: '6 hours ago',
      status: 'draft',
    },
    {
      id: 'f6',
      q: 'Do you see children?',
      a: 'From twelve upwards for dermatology and physiotherapy. Under twelve we refer to the Portland.',
      source: 'Who we treat',
      category: 'Appointments',
      uses: 38,
      confidence: 86,
      updated: '3 weeks ago',
      status: 'review',
    },
  ],
};

const solene: Brand = {
  id: 'solene',
  vertical: 'salon',
  name: 'Solène',
  legal: 'Solène Studio',
  kind: 'Hair studio · Shoreditch',
  scheme: 'light',
  currency: '£',
  address: '4 Redchurch Street, Shoreditch',
  district: 'London E2',
  phone: '+44 20 7946 0533',

  hero: {
    eyebrow: 'Colour specialists · Shoreditch',
    line1: 'Hair that grows',
    line2: 'out beautifully.',
    body: 'Cut for how it falls in six weeks, not just how it looks at the door. Colour by people who have been doing it for a decade.',
    cta: 'Book a chair',
    stats: [
      { value: '4.9', label: 'From 860 reviews' },
      { value: '6', label: 'Stylists' },
      { value: '10', label: 'Years open' },
    ],
  },
  nav: ['Services', 'Stylists', 'Retail', 'Journal'],

  images: {
    hero: 'photo-1633681926022-84c23e8cb2d6',
    feature: [
      'photo-1595475884562-073c30d45670',
      'photo-1521590832167-7bcbfaa6381f',
      'photo-1589729132389-8f0e0b55b91e',
    ],
    story: 'photo-1521590832167-7bcbfaa6381f',
  },
  story: {
    eyebrow: 'The studio',
    title: 'Cut for week six, not for the walk to the door.',
    body: 'Six stylists on Redchurch Street who have been doing this for a decade. Consultation first, always, and we will say no if it will not work.',
    points: [
      'Every colour starts with a patch test, 48 hours before',
      'Bond repair included on all lightening work',
      'Retail ships next day, free over fifty pounds',
    ],
  },
  marquee: ['Colour specialists', 'Cut & finish', 'Bond repair', 'Retail', 'Shoreditch'],
  process: [
    { title: 'Consultation first', note: 'We look at your hair, not a photograph on a phone.' },
    { title: 'Patch test', note: 'Forty-eight hours before any colour. Two minutes, no charge.' },
    { title: 'In the chair', note: 'Cut and colour built around how it grows, not how it sits today.' },
    { title: 'Growing it out', note: 'A plan for week six, and the products to hold it there.' },
  ],
  proof: [
    { value: '860+', label: 'Reviews' },
    { value: '10 yrs', label: 'On Redchurch St' },
  ],

  assistant: {
    greeting: "Hello — I'm Saint, front desk at Solène.",
    offer: 'I can book you a chair, match you to a stylist, or send products to your door.',
    nudgeTitle: 'Roots showing?',
    nudgeBody: 'Two cancellations opened up this week. Want me to hold one for you?',
    human: 'Iris Bellamy',
    humanRole: 'Studio manager',
  },

  skills: { order: true, reserve: false, appointment: true },
  itemNoun: 'service',
  itemNounPlural: 'services',
  tagNoun: 'Includes',
  peopleNoun: 'stylists',

  categories: [
    { id: 'cut', name: 'Cut & finish', note: 'Consultation always included' },
    { id: 'colour', name: 'Colour', note: 'Patch test 48 hours before' },
    { id: 'care', name: 'Treatments', note: 'Add to any appointment' },
    { id: 'retail', name: 'Retail', note: 'Delivered next day' },
  ],

  catalog: [
    {
      id: 's1',
      name: 'Cut & blow dry',
      categoryId: 'cut',
      price: 85,
      description: 'A proper consultation, a cut built around your growth pattern, finished dry.',
      tags: ['Consultation', 'Finish'],
      duration: '60 min',
      available: true,
      hue: 330,
      popular: true,
      sold: 318,
    },
    {
      id: 's2',
      name: 'Restyle',
      categoryId: 'cut',
      price: 120,
      description: 'Ninety minutes for a real change, with photographs and a plan for growing it out.',
      tags: ['90 min', 'Plan'],
      duration: '90 min',
      available: true,
      hue: 312,
      sold: 94,
    },
    {
      id: 's3',
      name: 'Full head highlights',
      categoryId: 'colour',
      price: 210,
      description: 'Hand-painted foils through the whole head, toned and finished. Allow three hours.',
      tags: ['Patch test', 'Toner', '3 hr'],
      duration: '180 min',
      available: true,
      hue: 44,
      popular: true,
      sold: 176,
    },
    {
      id: 's4',
      name: 'Root tint & gloss',
      categoryId: 'colour',
      price: 95,
      description: 'Regrowth covered and a gloss through the lengths to bring the tone back.',
      tags: ['Patch test', 'Gloss'],
      duration: '75 min',
      available: true,
      hue: 20,
      sold: 262,
    },
    {
      id: 's5',
      name: 'Balayage',
      categoryId: 'colour',
      price: 245,
      description: 'Freehand lightening for a soft grow-out, toned to the tone you actually asked for.',
      tags: ['Patch test', '3 hr'],
      duration: '180 min',
      available: false,
      hue: 36,
      sold: 131,
    },
    {
      id: 's6',
      name: 'Bond repair treatment',
      categoryId: 'care',
      price: 45,
      description: 'Twenty minutes under heat, rebuilding the bonds colour work takes out.',
      tags: ['20 min', 'Add-on'],
      duration: '20 min',
      available: true,
      hue: 288,
      sold: 208,
    },
    {
      id: 's7',
      name: 'Scalp ritual',
      categoryId: 'care',
      price: 38,
      description: 'Exfoliation, a long massage, and a light oil. Booked as an add-on or on its own.',
      tags: ['30 min', 'Massage'],
      duration: '30 min',
      available: true,
      hue: 156,
      sold: 141,
    },
    {
      id: 's8',
      name: 'Solène Repair Mask 200ml',
      categoryId: 'retail',
      price: 34,
      description: 'The mask we use in the basin, in a jar. Once a week, ten minutes, that is all.',
      tags: ['Vegan', '200 ml'],
      available: true,
      hue: 300,
      popular: true,
      sold: 386,
    },
    {
      id: 's9',
      name: 'Everyday Shampoo 300ml',
      categoryId: 'retail',
      price: 26,
      description: 'Sulphate-free, colour-safe, and it lathers properly — which most of them do not.',
      tags: ['Vegan', '300 ml'],
      available: true,
      hue: 190,
      sold: 421,
    },
    {
      id: 's10',
      name: 'Finishing Oil 50ml',
      categoryId: 'retail',
      price: 29,
      description: 'Two drops through the ends. Weightless, and it does not smell of coconut.',
      tags: ['50 ml'],
      available: true,
      hue: 40,
      sold: 254,
    },
  ],

  people: [
    {
      id: 'p1',
      name: 'Noa Bright',
      title: '',
      role: 'Creative director',
      focus: ['cut', 'colour'],
      rating: 5,
      reviews: 312,
      next: 'Fri, 10:00',
      hue: 330,
      bio: 'Twelve years cutting, six of them teaching. Books up about three weeks out.',
    },
    {
      id: 'p2',
      name: 'Malik Osei',
      title: '',
      role: 'Senior colourist',
      focus: ['colour', 'care'],
      rating: 4.9,
      reviews: 204,
      next: 'Today, 16:00',
      hue: 44,
      bio: 'Balayage and corrective colour. Unusually good with dark hair going lighter.',
    },
    {
      id: 'p3',
      name: 'Wren Tolliver',
      title: '',
      role: 'Stylist',
      focus: ['cut', 'care'],
      rating: 4.8,
      reviews: 118,
      next: 'Today, 12:30',
      hue: 288,
      bio: 'Curls, fringes and short cuts. Trained under Noa for four years.',
    },
    {
      id: 'p4',
      name: 'Elif Kaya',
      title: '',
      role: 'Colourist',
      focus: ['colour'],
      rating: 4.9,
      reviews: 96,
      next: 'Tomorrow, 09:30',
      hue: 20,
      bio: 'Tonal work and grey blending, with a very light touch on the scissors.',
    },
  ],

  hours: [
    { day: 'Tuesday – Friday', hours: '09:00 – 20:00' },
    { day: 'Saturday', hours: '09:00 – 18:00' },
    { day: 'Sunday', hours: '11:00 – 17:00' },
    { day: 'Monday', hours: 'Closed' },
  ],

  faq: [
    {
      id: 'f1',
      q: 'Do I need a patch test?',
      a: 'For any colour, yes — 48 hours before, and it takes two minutes. I can post you one or you can drop in.',
      source: 'Colour safety',
      category: 'Colour',
      uses: 268,
      confidence: 99,
      updated: '3 days ago',
      status: 'live',
    },
    {
      id: 'f2',
      q: 'How much is balayage?',
      a: 'From £245 with a senior colourist, including toner and finish. Long or very dark hair may need a second session.',
      source: 'Price list',
      category: 'Pricing',
      uses: 197,
      confidence: 95,
      updated: '1 week ago',
      status: 'live',
    },
    {
      id: 'f3',
      q: 'What if I need to cancel?',
      a: 'Free up to 48 hours before. Inside that we ask for 50%, because the chair usually goes empty.',
      source: 'Cancellation policy',
      category: 'Policies',
      uses: 134,
      confidence: 98,
      updated: '2 weeks ago',
      status: 'live',
    },
    {
      id: 'f4',
      q: 'Do you do hair extensions?',
      a: 'Tape and micro-ring, by consultation only. Noa and Elif fit them; allow two hours.',
      source: 'Extensions',
      category: 'Services',
      uses: 88,
      confidence: 87,
      updated: '1 month ago',
      status: 'live',
    },
    {
      id: 'f5',
      q: 'Can I buy products online?',
      a: 'Yes — everything on the retail shelf ships next day, free over £50.',
      source: 'Retail & delivery',
      category: 'Retail',
      uses: 71,
      confidence: 91,
      updated: '5 days ago',
      status: 'live',
    },
    {
      id: 'f6',
      q: 'Is there a student discount?',
      a: '20% off cuts on Tuesdays and Wednesdays with a valid card, excluding colour.',
      source: 'Offers',
      category: 'Pricing',
      uses: 44,
      confidence: 79,
      updated: '2 months ago',
      status: 'review',
    },
  ],
};

export const BRANDS: Record<BrandId, Brand> = { lumiere, aurelia, solene };
export const BRAND_ORDER: BrandId[] = ['lumiere', 'aurelia', 'solene'];
