import type { Brand, BrandId } from './types';

/* ==========================================================================
   Three worked examples. Swap these objects for API responses and the whole
   product — site, widget, console — re-skins and re-behaves.
   ========================================================================== */

export const PRODUCT = {
  name: 'Saint',
  line: 'The assistant that books, sells and answers.',
};

const lumiere: Brand = {
  id: 'lumiere',
  vertical: 'restaurant',
  name: 'Lumière',
  legal: 'Lumière Halal Kitchen',
  kind: 'Halal restaurant · Bukit Bintang',
  scheme: 'dark',
  currency: 'RM ',
  address: '24 Jalan Berangan, Bukit Bintang',
  district: '50200 Kuala Lumpur',
  phone: '+60 3-2148 8787',

  hero: {
    eyebrow: '100% halal · Malaysian comfort food · Bukit Bintang',
    line1: 'Big sambal energy,',
    line2: 'proper comfort.',
    body: 'Ayam gepuk pounded to order, juicy smash burgers and Malaysian sides made for sharing. Dine in, tapau, or have tonight delivered.',
    cta: 'Order makan',
    stats: [
      { value: '30', label: 'Minute delivery' },
      { value: '4.8', label: 'From 1,860 reviews' },
      { value: '100%', label: 'Halal kitchen' },
    ],
  },
  nav: ['Menu', 'Our story', 'Group dining', 'Find us'],

  images: {
    hero: 'photo-1517248135467-4c7edcad34c4',
    feature: [
      'zVTfYVY9HY0',
      'BzJwSCcQLJs',
      'zuVfkVxb8kg',
    ],
    story: 'o5UmAx8vEjg',
  },
  story: {
    eyebrow: 'Made in KL',
    title: 'Malaysian comfort food, turned all the way up.',
    body: 'We started with one mortar, a family sambal recipe and the belief that quick food should still feel properly cooked. Every chicken leg is fried fresh, every sambal is pounded in small batches, and the kitchen is 100% halal.',
    points: [
      'Four sambal heat levels, all pounded fresh through service',
      '100% halal ingredients and an alcohol-free dining room',
      'Delivery across central KL, usually within thirty minutes',
    ],
  },
  marquee: ['Ayam gepuk', 'Smash burgers', 'Fresh sambal', '100% halal', 'Bukit Bintang'],
  process: [
    { title: 'Pick your main', note: 'Ayam gepuk, a smash burger, or nasi lemak ayam berempah.' },
    { title: 'Choose the heat', note: 'From friendly pedas to our full-power sambal bawang.' },
    { title: 'Fried fresh', note: 'Every order is cooked when the ticket lands—nothing waits under a lamp.' },
    { title: 'Dine in or tapau', note: 'Take a table in Bukit Bintang or get it delivered across central KL.' },
  ],
  proof: [
    { value: '1,860+', label: 'Reviews' },
    { value: '100%', label: 'Halal kitchen' },
  ],

  assistant: {
    greeting: "Hai — I'm Saint, front of house at Lumière Halal Kitchen.",
    offer: 'I can take your order, book a table, or help you find the right sambal level.',
    nudgeTitle: 'Lapar?',
    nudgeBody: 'The kitchen is still firing. I can have ayam gepuk at your door in about thirty minutes.',
    human: 'Farah Aziz',
    humanRole: 'Restaurant manager',
  },

  skills: { order: true, reserve: true, appointment: false },
  itemNoun: 'dish',
  itemNounPlural: 'dishes',
  tagNoun: 'Allergens',
  peopleNoun: 'team',

  categories: [
    { id: 'geprek', name: 'Ayam gepuk', note: 'Rice, soup, cucumber and house sambal' },
    { id: 'burgers', name: 'Burgers', note: 'Smashed, stacked and fully halal' },
    { id: 'sides', name: 'Sides & sweet', note: 'For the table—or just for you' },
    { id: 'drinks', name: 'Drinks', note: 'Cold, local and alcohol-free' },
  ],

  catalog: [
    {
      id: 'l1',
      name: 'Ayam Gepuk Sambal Bawang',
      categoryId: 'geprek',
      price: 18.9,
      description: 'Crispy chicken leg, steamed rice, fried tofu, tempeh, cucumber and punchy sambal bawang.',
      tags: ['Spicy', 'Peanuts'],
      available: true,
      hue: 38,
      popular: true,
      sold: 412,
    },
    {
      id: 'l2',
      name: 'Ayam Gepuk Sambal Hijau',
      categoryId: 'geprek',
      price: 19.9,
      description: 'Our signature fried chicken with a bright green chilli sambal, rice, tofu and tempeh.',
      tags: ['Medium spicy', 'Peanuts'],
      available: true,
      hue: 18,
      popular: true,
      sold: 288,
    },
    {
      id: 'l3',
      name: 'Nasi Lemak Ayam Berempah',
      categoryId: 'geprek',
      price: 16.9,
      description: 'Coconut rice, crisp spiced chicken, ikan bilis, peanuts, egg and house sambal.',
      tags: ['Egg', 'Peanuts'],
      available: true,
      hue: 52,
      sold: 196,
    },
    {
      id: 'l4',
      name: 'Ayam Gepuk Sambal Gila',
      categoryId: 'geprek',
      price: 20.9,
      description: 'Extra-crispy chicken with our hottest raw chilli sambal. Serious heat, no refunds.',
      tags: ['Extra spicy', 'Peanuts'],
      available: false,
      hue: 8,
      sold: 174,
    },
    {
      id: 'l5',
      name: 'Lumière Spicy Smash',
      categoryId: 'burgers',
      price: 22.9,
      description: 'Double halal beef patties, American cheese, caramelised onions, pickles and sambal mayo.',
      tags: ['Gluten', 'Dairy', 'Egg'],
      available: true,
      hue: 190,
      popular: true,
      sold: 231,
    },
    {
      id: 'l6',
      name: 'Crispy Chicken Burger',
      categoryId: 'burgers',
      price: 19.9,
      description: 'Buttermilk-fried chicken thigh, crunchy slaw, pickles and smoky chilli sauce.',
      tags: ['Gluten', 'Dairy', 'Egg'],
      available: true,
      hue: 0,
      sold: 208,
    },
    {
      id: 'l7',
      name: 'Beef Rendang Burger',
      categoryId: 'burgers',
      price: 24.9,
      description: 'Smashed beef, dry rendang, crispy onions and cucumber acar in a toasted brioche bun.',
      tags: ['Gluten', 'Dairy'],
      available: true,
      hue: 44,
      sold: 143,
    },
    {
      id: 'l8',
      name: 'Cheesy Sambal Fries',
      categoryId: 'sides',
      price: 12.9,
      description: 'Skin-on fries, cheese sauce, crispy shallots and a spoon of house sambal.',
      tags: ['Dairy', 'Vegetarian'],
      available: true,
      hue: 30,
      sold: 97,
    },
    {
      id: 'l9',
      name: 'Pandan Gula Melaka Cheesecake',
      categoryId: 'sides',
      price: 14.9,
      description: 'Burnt cheesecake scented with pandan and finished with smoky gula Melaka caramel.',
      tags: ['Dairy', 'Egg', 'Gluten'],
      available: true,
      hue: 34,
      popular: true,
      sold: 356,
    },
    {
      id: 'l10',
      name: 'Tempeh Crunch',
      categoryId: 'sides',
      price: 8.9,
      description: 'Crisp tempeh tossed with sweet soy, chilli and toasted sesame.',
      tags: ['Soy', 'Sesame', 'Vegan'],
      available: true,
      hue: 22,
      sold: 164,
    },
    {
      id: 'l11',
      name: 'Kopi Susu Gula Melaka',
      categoryId: 'drinks',
      price: 8.9,
      description: 'Strong local coffee, fresh milk and gula Melaka over ice.',
      tags: ['Dairy'],
      available: true,
      hue: 340,
      sold: 189,
    },
    {
      id: 'l12',
      name: 'Teh O Ais Limau',
      categoryId: 'drinks',
      price: 5.9,
      description: 'Pulled black tea, calamansi and plenty of ice. Sweetness adjustable.',
      tags: ['Vegan'],
      available: true,
      hue: 46,
      sold: 152,
    },
  ],

  people: [],

  hours: [
    { day: 'Monday – Thursday', hours: '11:30 – 22:30' },
    { day: 'Friday – Saturday', hours: '11:30 – 23:30' },
    { day: 'Sunday', hours: '11:30 – 22:00' },
  ],

  faq: [
    {
      id: 'f1',
      q: 'Do you take walk-ins?',
      a: 'Always. We keep the counter and several two-tops for walk-ins, though groups of five or more should book.',
      source: 'Booking policy',
      category: 'Reservations',
      uses: 214,
      confidence: 97,
      updated: '2 days ago',
      status: 'live',
    },
    {
      id: 'f2',
      q: 'How far do you deliver?',
      a: 'We deliver across central Kuala Lumpur, including Bukit Bintang, KLCC, TRX, Pudu and Kampung Baru. Most orders arrive within thirty minutes.',
      source: 'Delivery zones',
      category: 'Delivery',
      uses: 189,
      confidence: 99,
      updated: 'Yesterday',
      status: 'live',
    },
    {
      id: 'f3',
      q: 'Can you cater for allergies?',
      a: 'Yes. Every dish is tagged, and the kitchen adjusts most plates. Tell me the allergy and I will flag it on the order.',
      source: 'Allergen handling',
      category: 'Kitchen',
      uses: 147,
      confidence: 94,
      updated: '5 days ago',
      status: 'live',
    },
    {
      id: 'f4',
      q: 'Is everything halal?',
      a: 'Yes. The whole menu uses halal ingredients, pork and lard never enter the kitchen, and no alcohol is served.',
      source: 'Halal policy',
      category: 'Kitchen',
      uses: 76,
      confidence: 92,
      updated: '3 weeks ago',
      status: 'live',
    },
    {
      id: 'f5',
      q: 'Can you host a group makan?',
      a: 'Yes. The upstairs room seats 32, with sharing menus from RM 55 per person. Larger buyouts are available on request.',
      source: 'Group dining',
      category: 'Events',
      uses: 52,
      confidence: 88,
      updated: '1 month ago',
      status: 'review',
    },
    {
      id: 'f6',
      q: 'Is there parking nearby?',
      a: 'Paid parking is available at The Robertson and Pavilion Kuala Lumpur. Bukit Bintang MRT is about seven minutes away on foot.',
      source: 'Finding us',
      category: 'Visiting',
      uses: 41,
      confidence: 84,
      updated: '2 months ago',
      status: 'draft',
    },
  ],
};

const aurelia: Brand = {
  id: 'aurelia',
  vertical: 'clinic',
  name: 'Aurelia',
  legal: 'Aurelia Specialist Clinic',
  kind: 'Private clinic · Bangsar',
  scheme: 'light',
  currency: 'RM ',
  address: '17 Jalan Telawi 3, Bangsar Baru',
  district: '59100 Kuala Lumpur',
  phone: '+60 3-2201 1868',

  hero: {
    eyebrow: 'Private multidisciplinary clinic · Bangsar, KL',
    line1: 'Considered care,',
    line2: 'unhurried.',
    body: 'Forty-minute appointments as standard, four specialists under one roof, and bilingual support when you need a clear answer—not a rushed one.',
    cta: 'Find an appointment',
    stats: [
      { value: '4.9', label: 'Patient rating' },
      { value: '40', label: 'Minute visits' },
      { value: '24/7', label: 'Booking line' },
    ],
  },
  nav: ['Treatments', 'Our team', 'Visiting', 'Journal'],

  images: {
    hero: '7-l5EL7YHI4',
    feature: [
      'AaVTg7jXUew',
      'DbCfSrTnflA',
      '4e017fuMeXE',
    ],
    story: 'GBcLdqOBbXE',
  },
  story: {
    eyebrow: 'How we work',
    title: 'Forty minutes, because ten was never enough.',
    body: 'Four specialists, one building, and notes that follow you between them. You leave with a written plan rather than a leaflet.',
    points: [
      'Same-week appointments, most weeks same-day',
      'Panel billing with AIA, Prudential, Great Eastern and Allianz',
      'Step-free throughout, with lift access and basement parking',
    ],
  },
  marquee: ['General medicine', 'Dermatology', 'Dental', 'Physiotherapy', 'Bangsar'],
  process: [
    { title: 'Private consultation', note: 'History, examination and goals reviewed. No obligation.' },
    { title: 'A written plan', note: 'What we recommend, what it costs, and what it will not fix.' },
    { title: 'Your appointment', note: 'Forty minutes as standard, with the clinician you chose.' },
    { title: 'Follow-up', note: 'A review within fourteen days, included in the fee.' },
  ],
  proof: [
    { value: '2,400+', label: 'Appointments' },
    { value: '14 yrs', label: 'Experience' },
  ],

  assistant: {
    greeting: "Good day — I'm Saint, the concierge for Aurelia Clinic.",
    offer: 'I can book you in, move an appointment, or answer anything about the clinic.',
    nudgeTitle: 'Need a slot this week?',
    nudgeBody: 'I can check the diary and book you in — it takes about thirty seconds.',
    human: 'Siti Hajar',
    humanRole: 'Patient coordinator',
  },

  skills: { order: false, reserve: false, appointment: true },
  itemNoun: 'treatment',
  itemNounPlural: 'treatments',
  tagNoun: 'Includes',
  peopleNoun: 'clinicians',

  categories: [
    { id: 'general', name: 'General medicine', note: 'Whole-picture consultations' },
    { id: 'derm', name: 'Dermatology', note: 'Skin, hair and nails' },
    { id: 'dental', name: 'Dental', note: 'Hygiene and restorative' },
    { id: 'physio', name: 'Physiotherapy', note: 'Movement and recovery' },
  ],

  catalog: [
    {
      id: 'a1',
      name: 'General consultation',
      categoryId: 'general',
      price: 160,
      description:
        'A full forty minutes with one of our physicians, including examination and a written plan.',
      tags: ['Written plan', 'Referrals'],
      duration: '40 min',
      available: true,
      hue: 168,
      popular: true,
      sold: 186,
    },
    {
      id: 'a2',
      name: 'Annual health review',
      categoryId: 'general',
      price: 680,
      description: 'Bloods, ECG, lung function and a ninety-minute review of the results with you.',
      tags: ['Bloods', 'ECG', '90 min'],
      duration: '90 min',
      available: true,
      hue: 186,
      sold: 64,
    },
    {
      id: 'a3',
      name: 'Mole mapping & skin check',
      categoryId: 'derm',
      price: 320,
      description:
        'Full-body dermoscopy, photographed and compared against your previous visit.',
      tags: ['Photography', 'Report'],
      duration: '45 min',
      available: true,
      hue: 24,
      popular: true,
      sold: 142,
    },
    {
      id: 'a4',
      name: 'Acne & rosacea consultation',
      categoryId: 'derm',
      price: 250,
      description: 'Assessment, a prescription where appropriate, and a six-week follow-up included.',
      tags: ['Prescription', 'Follow-up'],
      duration: '40 min',
      available: true,
      hue: 8,
      sold: 98,
    },
    {
      id: 'a5',
      name: 'Hygiene & six-month check',
      categoryId: 'dental',
      price: 180,
      description: 'Scale, polish, and a full examination with small X-rays if they are due.',
      tags: ['X-rays', 'Polish'],
      duration: '40 min',
      available: true,
      hue: 200,
      sold: 224,
    },
    {
      id: 'a6',
      name: 'Composite bonding',
      categoryId: 'dental',
      price: 650,
      description: 'Per tooth, shade-matched and finished in a single visit.',
      tags: ['Single visit'],
      duration: '60 min',
      available: false,
      hue: 46,
      sold: 37,
    },
    {
      id: 'a7',
      name: 'Physiotherapy session',
      categoryId: 'physio',
      price: 180,
      description: 'Movement assessment, hands-on treatment, and exercises you will actually do.',
      tags: ['Hands-on', 'Home plan'],
      duration: '50 min',
      available: true,
      hue: 148,
      popular: true,
      sold: 176,
    },
    {
      id: 'a8',
      name: 'Running gait analysis',
      categoryId: 'physio',
      price: 260,
      description: 'Treadmill filming from four angles, with a written report and load plan.',
      tags: ['Video', 'Report'],
      duration: '60 min',
      available: true,
      hue: 210,
      sold: 52,
    },
  ],

  people: [
    {
      id: 'p1',
      name: 'Aisha Rahman',
      title: 'Dr',
      role: 'General medicine',
      focus: ['general', 'derm'],
      rating: 4.9,
      reviews: 218,
      next: 'Today, 15:30',
      hue: 168,
      bio: 'Fifteen years in family medicine, with a special interest in women’s health and long-term fatigue.',
    },
    {
      id: 'p2',
      name: 'Lim Wei Jian',
      title: 'Dr',
      role: 'Dermatology',
      focus: ['derm', 'general'],
      rating: 4.8,
      reviews: 164,
      next: 'Tomorrow, 09:00',
      hue: 24,
      bio: 'Consultant dermatologist specialising in mole mapping, eczema and skin cancer surveillance.',
    },
    {
      id: 'p3',
      name: 'Nur Izzati Ismail',
      title: 'Dr',
      role: 'Dental surgery',
      focus: ['dental'],
      rating: 5,
      reviews: 91,
      next: 'Today, 17:00',
      hue: 200,
      bio: 'Restorative and cosmetic dentistry with a calm, conservative approach.',
    },
    {
      id: 'p4',
      name: 'Kavitha Nair',
      title: 'Ms',
      role: 'Physiotherapy',
      focus: ['physio'],
      rating: 4.9,
      reviews: 143,
      next: 'Thu, 11:15',
      hue: 148,
      bio: 'Musculoskeletal physiotherapist who works with runners and desk-bound backs across KL.',
    },
  ],

  hours: [
    { day: 'Monday – Thursday', hours: '08:00 – 19:00' },
    { day: 'Friday', hours: '08:00 – 17:30' },
    { day: 'Saturday', hours: '09:00 – 14:00' },
    { day: 'Sunday', hours: 'Closed' },
  ],

  faq: [
    {
      id: 'f1',
      q: 'Which insurers do you accept?',
      a: 'We support panel and guarantee-letter billing for AIA, Prudential, Great Eastern and Allianz. Other providers can usually be claimed with our itemised receipt.',
      source: 'Insurance & billing',
      category: 'Billing',
      uses: 231,
      confidence: 98,
      updated: '4 days ago',
      status: 'live',
    },
    {
      id: 'f2',
      q: 'Do I need a referral?',
      a: 'Not for anything on our list. If your insurer needs a referral letter, your GP or panel clinic can send it directly to us.',
      source: 'Before your visit',
      category: 'Appointments',
      uses: 178,
      confidence: 96,
      updated: '1 week ago',
      status: 'live',
    },
    {
      id: 'f3',
      q: 'What is your cancellation policy?',
      a: 'Free up to 24 hours before. Inside 24 hours we charge half the fee, waived if you are unwell.',
      source: 'Cancellation policy',
      category: 'Policies',
      uses: 142,
      confidence: 99,
      updated: 'Yesterday',
      status: 'live',
    },
    {
      id: 'f4',
      q: 'Is the clinic step-free?',
      a: 'Yes. The Jalan Telawi entrance is level, a lift reaches the clinic, and accessible bays are available in the basement.',
      source: 'Access & parking',
      category: 'Visiting',
      uses: 97,
      confidence: 93,
      updated: '2 weeks ago',
      status: 'live',
    },
    {
      id: 'f5',
      q: 'Can I get a repeat prescription?',
      a: 'If we prescribed it in the last six months, yes — usually the same working day.',
      source: 'Prescriptions',
      category: 'Treatments',
      uses: 64,
      confidence: 74,
      updated: '6 hours ago',
      status: 'draft',
    },
    {
      id: 'f6',
      q: 'Do you see children?',
      a: 'From twelve upwards for dermatology and physiotherapy. Younger children are referred to our paediatric partners at University Malaya Medical Centre.',
      source: 'Who we treat',
      category: 'Appointments',
      uses: 38,
      confidence: 86,
      updated: '3 weeks ago',
      status: 'review',
    },
  ],
};

const solene: Brand = {
  id: 'solene',
  vertical: 'salon',
  name: 'Solène',
  legal: 'Solène Hair Studio',
  kind: 'Hair studio · Bangsar',
  scheme: 'light',
  currency: 'RM ',
  address: '63-1 Jalan Telawi 3, Bangsar Baru',
  district: '59100 Kuala Lumpur',
  phone: '+60 3-2282 0533',

  hero: {
    eyebrow: 'Colour specialists · Bangsar, Kuala Lumpur',
    line1: 'Hair that grows',
    line2: 'out beautifully.',
    body: 'Cut for how it falls in six weeks and styled for Malaysian heat and humidity. Colour by people who understand every hair texture in KL.',
    cta: 'Book a chair',
    stats: [
      { value: '4.9', label: 'From 860 reviews' },
      { value: '6', label: 'Stylists' },
      { value: '10', label: 'Years in Bangsar' },
    ],
  },
  nav: ['Services', 'Stylists', 'Retail', 'Journal'],

  images: {
    hero: 'photo-1633681926022-84c23e8cb2d6',
    feature: [
      'photo-1595475884562-073c30d45670',
      'photo-1521590832167-7bcbfaa6381f',
      'photo-1589729132389-8f0e0b55b91e',
    ],
    story: 'photo-1521590832167-7bcbfaa6381f',
  },
  story: {
    eyebrow: 'The studio',
    title: 'Cut for week six, not for the walk to the door.',
    body: 'Six stylists in Bangsar who have been doing this for a decade. Consultation first, always, with cuts and colour designed for how hair behaves in Malaysian weather.',
    points: [
      'Every colour starts with a patch test, 48 hours before',
      'Bond repair included on all lightening work',
      'Same-day Klang Valley delivery, free over RM 150',
    ],
  },
  marquee: ['Colour specialists', 'Cut & finish', 'Bond repair', 'Retail', 'Bangsar'],
  process: [
    { title: 'Consultation first', note: 'We look at your hair, not a photograph on a phone.' },
    { title: 'Patch test', note: 'Forty-eight hours before any colour. Two minutes, no charge.' },
    { title: 'In the chair', note: 'Cut and colour built around how it grows, not how it sits today.' },
    { title: 'Growing it out', note: 'A plan for week six, and the products to hold it there.' },
  ],
  proof: [
    { value: '860+', label: 'Reviews' },
    { value: '10 yrs', label: 'In Bangsar' },
  ],

  assistant: {
    greeting: "Hello — I'm Saint, front desk at Solène.",
    offer: 'I can book you a chair, match you to a stylist, or send products to your door.',
    nudgeTitle: 'Roots showing?',
    nudgeBody: 'Two cancellations opened up this week. Want me to hold one for you?',
    human: 'Nadia Farouk',
    humanRole: 'Studio manager',
  },

  skills: { order: true, reserve: false, appointment: true },
  itemNoun: 'service',
  itemNounPlural: 'services',
  tagNoun: 'Includes',
  peopleNoun: 'stylists',

  categories: [
    { id: 'cut', name: 'Cut & finish', note: 'Consultation always included' },
    { id: 'colour', name: 'Colour', note: 'Patch test 48 hours before' },
    { id: 'care', name: 'Treatments', note: 'Add to any appointment' },
    { id: 'retail', name: 'Retail', note: 'Same-day in the Klang Valley' },
  ],

  catalog: [
    {
      id: 's1',
      name: 'Cut & blow dry',
      categoryId: 'cut',
      price: 150,
      description: 'A proper consultation, a cut built around your growth pattern, finished dry.',
      tags: ['Consultation', 'Finish'],
      duration: '60 min',
      available: true,
      hue: 330,
      popular: true,
      sold: 318,
    },
    {
      id: 's2',
      name: 'Restyle',
      categoryId: 'cut',
      price: 220,
      description: 'Ninety minutes for a real change, with photographs and a plan for growing it out.',
      tags: ['90 min', 'Plan'],
      duration: '90 min',
      available: true,
      hue: 312,
      sold: 94,
    },
    {
      id: 's3',
      name: 'Full head highlights',
      categoryId: 'colour',
      price: 480,
      description: 'Hand-painted foils through the whole head, toned and finished. Allow three hours.',
      tags: ['Patch test', 'Toner', '3 hr'],
      duration: '180 min',
      available: true,
      hue: 44,
      popular: true,
      sold: 176,
    },
    {
      id: 's4',
      name: 'Root tint & gloss',
      categoryId: 'colour',
      price: 220,
      description: 'Regrowth covered and a gloss through the lengths to bring the tone back.',
      tags: ['Patch test', 'Gloss'],
      duration: '75 min',
      available: true,
      hue: 20,
      sold: 262,
    },
    {
      id: 's5',
      name: 'Balayage',
      categoryId: 'colour',
      price: 580,
      description: 'Freehand lightening for a soft grow-out, toned to the tone you actually asked for.',
      tags: ['Patch test', '3 hr'],
      duration: '180 min',
      available: false,
      hue: 36,
      sold: 131,
    },
    {
      id: 's6',
      name: 'Bond repair treatment',
      categoryId: 'care',
      price: 90,
      description: 'Twenty minutes under heat, rebuilding the bonds colour work takes out.',
      tags: ['20 min', 'Add-on'],
      duration: '20 min',
      available: true,
      hue: 288,
      sold: 208,
    },
    {
      id: 's7',
      name: 'Scalp ritual',
      categoryId: 'care',
      price: 80,
      description: 'Exfoliation, a long massage, and a light oil. Booked as an add-on or on its own.',
      tags: ['30 min', 'Massage'],
      duration: '30 min',
      available: true,
      hue: 156,
      sold: 141,
    },
    {
      id: 's8',
      name: 'Solène Repair Mask 200ml',
      categoryId: 'retail',
      price: 110,
      description: 'The mask we use in the basin, in a jar. Once a week, ten minutes, that is all.',
      tags: ['Vegan', '200 ml'],
      available: true,
      hue: 300,
      popular: true,
      sold: 386,
    },
    {
      id: 's9',
      name: 'Everyday Shampoo 300ml',
      categoryId: 'retail',
      price: 85,
      description: 'Sulphate-free, colour-safe, and it lathers properly — which most of them do not.',
      tags: ['Vegan', '300 ml'],
      available: true,
      hue: 190,
      sold: 421,
    },
    {
      id: 's10',
      name: 'Finishing Oil 50ml',
      categoryId: 'retail',
      price: 95,
      description: 'Two drops through the ends. Weightless, and it does not smell of coconut.',
      tags: ['50 ml'],
      available: true,
      hue: 40,
      sold: 254,
    },
  ],

  people: [
    {
      id: 'p1',
      name: 'Nadia Farouk',
      title: '',
      role: 'Creative director',
      focus: ['cut', 'colour'],
      rating: 5,
      reviews: 312,
      next: 'Fri, 10:00',
      hue: 330,
      bio: 'Twelve years cutting, six of them teaching. Books up about three weeks out.',
    },
    {
      id: 'p2',
      name: 'Marcus Tan',
      title: '',
      role: 'Senior colourist',
      focus: ['colour', 'care'],
      rating: 4.9,
      reviews: 204,
      next: 'Today, 16:00',
      hue: 44,
      bio: 'Balayage and corrective colour, especially dark Asian hair going lighter without losing condition.',
    },
    {
      id: 'p3',
      name: 'Aina Ismail',
      title: '',
      role: 'Stylist',
      focus: ['cut', 'care'],
      rating: 4.8,
      reviews: 118,
      next: 'Today, 12:30',
      hue: 288,
      bio: 'Curls, hijab-friendly consultations, fringes and short cuts. Trained under Nadia for four years.',
    },
    {
      id: 'p4',
      name: 'Mei Lin Wong',
      title: '',
      role: 'Colourist',
      focus: ['colour'],
      rating: 4.9,
      reviews: 96,
      next: 'Tomorrow, 09:30',
      hue: 20,
      bio: 'Tonal work and grey blending, with a very light touch on the scissors.',
    },
  ],

  hours: [
    { day: 'Tuesday – Friday', hours: '09:00 – 20:00' },
    { day: 'Saturday', hours: '09:00 – 18:00' },
    { day: 'Sunday', hours: '11:00 – 17:00' },
    { day: 'Monday', hours: 'Closed' },
  ],

  faq: [
    {
      id: 'f1',
      q: 'Do I need a patch test?',
      a: 'For any colour, yes — 48 hours before, and it takes two minutes. I can post you one or you can drop in.',
      source: 'Colour safety',
      category: 'Colour',
      uses: 268,
      confidence: 99,
      updated: '3 days ago',
      status: 'live',
    },
    {
      id: 'f2',
      q: 'How much is balayage?',
      a: 'From RM 580 with a senior colourist, including toner and finish. Long or very dark hair may need a second session.',
      source: 'Price list',
      category: 'Pricing',
      uses: 197,
      confidence: 95,
      updated: '1 week ago',
      status: 'live',
    },
    {
      id: 'f3',
      q: 'What if I need to cancel?',
      a: 'Free up to 48 hours before. Inside that we ask for 50%, because the chair usually goes empty.',
      source: 'Cancellation policy',
      category: 'Policies',
      uses: 134,
      confidence: 98,
      updated: '2 weeks ago',
      status: 'live',
    },
    {
      id: 'f4',
      q: 'Do you do hair extensions?',
      a: 'Tape and micro-ring, by consultation only. Nadia and Mei Lin fit them; allow two hours.',
      source: 'Extensions',
      category: 'Services',
      uses: 88,
      confidence: 87,
      updated: '1 month ago',
      status: 'live',
    },
    {
      id: 'f5',
      q: 'Can I buy products online?',
      a: 'Yes—same-day delivery is available across the Klang Valley, and delivery is free over RM 150.',
      source: 'Retail & delivery',
      category: 'Retail',
      uses: 71,
      confidence: 91,
      updated: '5 days ago',
      status: 'live',
    },
    {
      id: 'f6',
      q: 'Is there a student discount?',
      a: '15% off cuts from Tuesday to Thursday with a valid Malaysian student card, excluding colour.',
      source: 'Offers',
      category: 'Pricing',
      uses: 44,
      confidence: 79,
      updated: '2 months ago',
      status: 'review',
    },
  ],
};

export const BRANDS: Record<BrandId, Brand> = { lumiere, aurelia, solene };
export const BRAND_ORDER: BrandId[] = ['lumiere', 'aurelia', 'solene'];
