import type { Brand, BrandId } from './types';

/* ==========================================================================
   Three worked examples. Swap these objects for API responses and the whole
   product — site, widget, console — re-skins and re-behaves.
   ========================================================================== */

export const PRODUCT = {
  name: 'Saint',
  line: 'The assistant that books, sells and answers.',
};

const lumiere: Brand = {
  id: 'lumiere',
  vertical: 'restaurant',
  name: 'Seroja',
  legal: 'Seroja Halal Kitchen',
  kind: 'Malaysian halal kitchen · Kampung Baru',
  scheme: 'dark',
  currency: 'RM ',
  address: '18 Jalan Raja Muda Musa, Kampung Baru',
  district: '50300 Kuala Lumpur',
  phone: '+60 3-2691 1848',

  hero: {
    eyebrow: '100% halal · fire-grilled · sambal pounded daily',
    line1: 'Malaysian soul,',
    line2: 'served with fire.',
    body: 'A modern halal kitchen in Kampung Baru, cooking ayam gepuk, nasi classics and charcoal-grilled burgers with the flavours we grew up with.',
    cta: 'Order makan',
    stats: [
      { value: '30', label: 'Minute delivery' },
      { value: '4.9', label: 'From 2,140 reviews' },
      { value: '100%', label: 'Halal kitchen' },
    ],
  },
  nav: ['Menu', 'Our kitchen', 'Group dining', 'Find us'],

  images: {
    hero: 'photo-1517248135467-4c7edcad34c4',
    feature: [
      'photo-1604908176997-125f25cc6f3d',
      'photo-1568901346375-23c9450c58cd',
      'photo-1603894584373-5ac82b2ae398',
    ],
    story: 'photo-1547592180-85f173990554',
  },
  story: {
    eyebrow: 'Our philosophy',
    title: 'Malaysian comfort, made slowly and shared generously.',
    body: 'We take the food Malaysians know by heart and give every part of it proper attention: sambal pounded in small batches, chicken fried to order and sauces built from real spice, not shortcuts.',
    points: [
      'A 100% halal kitchen with no pork, lard or alcohol',
      'Sambal, acar and rempah made from scratch every morning',
      'Dine in, tapau or delivery across central Kuala Lumpur',
    ],
  },
  marquee: ['Ayam gepuk', 'Nasi lemak', 'Charcoal grill', '100% halal', 'Kampung Baru'],
  process: [
    { title: 'Choose your comfort', note: 'Start with rice, ayam gepuk or something straight from the charcoal grill.' },
    { title: 'Pick your heat', note: 'Sambal comes friendly, pedas or full-power. We will always warn you.' },
    { title: 'Cooked when ordered', note: 'Chicken is fried fresh and every burger hits the grill after your ticket lands.' },
    { title: 'Makan your way', note: 'Take a table, tapau on the way home or get it delivered across central KL.' },
  ],
  proof: [
    { value: '2,140+', label: 'Happy diners' },
    { value: '100%', label: 'Halal kitchen' },
  ],

  assistant: {
    greeting: "Hai — I'm Saint, front of house at Seroja.",
    offer: 'I can take your order, book a table, or help you choose the right sambal level.',
    nudgeTitle: 'Lapar?',
    nudgeBody: 'The kitchen is firing now. I can have ayam gepuk at your door in around thirty minutes.',
    human: 'Farah Aziz',
    humanRole: 'Restaurant manager',
  },

  skills: { order: true, reserve: true, appointment: false },
  itemNoun: 'dish',
  itemNounPlural: 'dishes',
  tagNoun: 'Allergens',
  peopleNoun: 'team',

  categories: [
    { id: 'rice', name: 'Nasi & ayam', note: 'Rice plates with house sambal and sides' },
    { id: 'grill', name: 'Burgers & grill', note: 'Halal beef, crispy chicken and charcoal smoke' },
    { id: 'sides', name: 'Sides & sweet', note: 'Made for sharing, although nobody has to' },
    { id: 'drinks', name: 'Drinks', note: 'Cold, local and alcohol-free' },
  ],

  catalog: [
    {
      id: 'l1',
      name: 'Nasi Lemak Ayam Berempah',
      categoryId: 'rice',
      price: 22,
      description: 'Coconut rice, crisp spiced chicken, ikan bilis, peanuts, egg, cucumber and house sambal.',
      tags: ['Egg', 'Peanuts'],
      available: true,
      hue: 38,
      popular: true,
      sold: 412,
    },
    {
      id: 'l2',
      name: 'Ayam Gepuk Sambal Bawang',
      categoryId: 'rice',
      price: 21,
      description: 'Fresh-fried chicken, steamed rice, tofu, tempeh, cucumber and sambal pounded to order.',
      tags: ['Spicy', 'Peanuts'],
      available: true,
      hue: 18,
      popular: true,
      sold: 288,
    },
    {
      id: 'l3',
      name: 'Nasi Kerabu Ayam Percik',
      categoryId: 'rice',
      price: 24,
      description: 'Blue pea rice, charcoal chicken, kerisik, herbs, salted egg and a bright budu dressing.',
      tags: ['Egg', 'Fish'],
      available: true,
      hue: 52,
      sold: 196,
    },
    {
      id: 'l4',
      name: 'Daging Rendang Rice Bowl',
      categoryId: 'rice',
      price: 26,
      description: 'Slow-cooked halal beef rendang, turmeric cabbage, acar jelatah and steamed rice.',
      tags: ['Coconut', 'Medium spicy'],
      available: true,
      hue: 8,
      sold: 174,
    },
    {
      id: 'l5',
      name: 'Seroja Double Smash',
      categoryId: 'grill',
      price: 28,
      description: 'Two halal beef patties, cheddar, caramelised onion, pickles and smoky sambal mayo.',
      tags: ['Gluten', 'Dairy', 'Egg'],
      available: true,
      hue: 190,
      popular: true,
      sold: 231,
    },
    {
      id: 'l6',
      name: 'Crispy Sambal Chicken Burger',
      categoryId: 'grill',
      price: 24,
      description: 'Buttermilk-fried chicken thigh, crunchy slaw, pickles and sambal hijau in brioche.',
      tags: ['Gluten', 'Dairy', 'Egg'],
      available: true,
      hue: 0,
      sold: 208,
    },
    {
      id: 'l7',
      name: 'Satay Daging Arang',
      categoryId: 'grill',
      price: 18,
      description: 'Charcoal-grilled beef skewers with compressed rice, cucumber and roasted peanut sauce.',
      tags: ['Peanuts'],
      available: true,
      hue: 44,
      sold: 143,
    },
    {
      id: 'l8',
      name: 'Tempeh & Tauhu Berlada',
      categoryId: 'sides',
      price: 12,
      description: 'Crisp tempeh and tofu glazed with sweet soy, chilli, sesame and fried shallots.',
      tags: ['Soy', 'Sesame', 'Vegan'],
      available: true,
      hue: 30,
      sold: 97,
    },
    {
      id: 'l9',
      name: 'Pandan Gula Melaka Cheesecake',
      categoryId: 'sides',
      price: 15,
      description: 'Burnt cheesecake scented with pandan and finished with smoky gula Melaka caramel.',
      tags: ['Dairy', 'Egg', 'Gluten'],
      available: true,
      hue: 34,
      popular: true,
      sold: 356,
    },
    {
      id: 'l10',
      name: 'Cendol Soft Serve',
      categoryId: 'sides',
      price: 12,
      description: 'Coconut soft serve, pandan cendol, gula Melaka, red bean and toasted coconut.',
      tags: ['Dairy', 'Coconut'],
      available: true,
      hue: 22,
      sold: 164,
    },
    {
      id: 'l11',
      name: 'Teh Tarik Seroja',
      categoryId: 'drinks',
      price: 7,
      description: 'Strong pulled tea with fresh milk, served hot or over ice.',
      tags: ['Dairy'],
      available: true,
      hue: 340,
      sold: 189,
    },
    {
      id: 'l12',
      name: 'Asam Boi Calamansi',
      categoryId: 'drinks',
      price: 9,
      description: 'Fresh calamansi, sour plum, soda and plenty of ice.',
      tags: ['Vegan'],
      available: true,
      hue: 46,
      sold: 152,
    },
  ],

  people: [],

  hours: [
    { day: 'Monday – Thursday', hours: '11:30 – 22:30' },
    { day: 'Friday – Saturday', hours: '11:30 – 23:30' },
    { day: 'Sunday', hours: '11:30 – 22:00' },
  ],

  faq: [
    {
      id: 'f1',
      q: 'Do you take walk-ins?',
      a: 'Always. We keep the counter and several two-tops for walk-ins; groups of five or more should book ahead.',
      source: 'Booking policy',
      category: 'Reservations',
      uses: 214,
      confidence: 97,
      updated: '2 days ago',
      status: 'live',
    },
    {
      id: 'f2',
      q: 'How far do you deliver?',
      a: 'We deliver across central Kuala Lumpur, including Kampung Baru, KLCC, Bukit Bintang, TRX and Chow Kit. Most orders arrive within thirty minutes.',
      source: 'Delivery zones',
      category: 'Delivery',
      uses: 189,
      confidence: 99,
      updated: 'Yesterday',
      status: 'live',
    },
    {
      id: 'f3',
      q: 'Can you cater for allergies?',
      a: 'Yes. Every dish is tagged and the kitchen can adjust many plates. Tell us the allergy before ordering so a manager can confirm the safest options.',
      source: 'Allergen handling',
      category: 'Kitchen',
      uses: 147,
      confidence: 94,
      updated: '5 days ago',
      status: 'live',
    },
    {
      id: 'f4',
      q: 'Is everything halal?',
      a: 'Yes. Our whole menu uses halal-certified ingredients, pork and lard never enter the kitchen, and no alcohol is served.',
      source: 'Halal policy',
      category: 'Kitchen',
      uses: 76,
      confidence: 92,
      updated: '3 weeks ago',
      status: 'live',
    },
    {
      id: 'f5',
      q: 'Can you host a group makan?',
      a: 'Yes. Our upstairs room seats 32, with family-style menus from RM 65 per person. Full restaurant buyouts are available on request.',
      source: 'Group dining',
      category: 'Events',
      uses: 52,
      confidence: 88,
      updated: '1 month ago',
      status: 'review',
    },
    {
      id: 'f6',
      q: 'Is there parking nearby?',
      a: 'Paid parking is available at Quill City Mall and around Jalan Raja Muda Musa. Kampung Baru MRT is about six minutes away on foot.',
      source: 'Finding us',
      category: 'Visiting',
      uses: 41,
      confidence: 84,
      updated: '2 months ago',
      status: 'draft',
    },
  ],
};

const aurelia: Brand = {
  id: 'aurelia',
  vertical: 'clinic',
  name: 'Teduh',
  legal: 'Teduh Clinic',
  kind: 'Private clinic · Chelsea',
  scheme: 'light',
  currency: '£',
  address: '18 Marlowe Street, Chelsea',
  district: 'London SW3',
  phone: '+44 20 7946 0812',

  hero: {
    eyebrow: 'Private clinic · Chelsea, London',
    line1: 'Considered care,',
    line2: 'unhurried.',
    body: 'Forty-minute appointments as standard, four specialists under one roof, and someone who answers at two in the morning — because that is often when you need it.',
    cta: 'Find an appointment',
    stats: [
      { value: '4.9', label: 'Patient rating' },
      { value: '40', label: 'Minute visits' },
      { value: '24/7', label: 'Booking line' },
    ],
  },
  nav: ['Treatments', 'Our team', 'Visiting', 'Journal'],

  images: {
    hero: 'photo-1512290923902-8a9f81dc236c',
    feature: [
      'photo-1489278353717-f64c6ee8a4d2',
      'photo-1583416750470-965b2707b355',
      'photo-1540555700478-4be289fbecef',
    ],
    story: 'photo-1583416750470-965b2707b355',
  },
  story: {
    eyebrow: 'How we work',
    title: 'Forty minutes, because ten was never enough.',
    body: 'Four specialists, one building, and notes that follow you between them. You leave with a written plan rather than a leaflet.',
    points: [
      'Same-week appointments, most weeks same-day',
      'Direct billing with Bupa, AXA, Vitality and Aviva',
      'Step-free throughout, with blue-badge bays outside',
    ],
  },
  marquee: ['General medicine', 'Dermatology', 'Dental', 'Physiotherapy', 'Chelsea'],
  process: [
    { title: 'Private consultation', note: 'History, examination and goals reviewed. No obligation.' },
    { title: 'A written plan', note: 'What we recommend, what it costs, and what it will not fix.' },
    { title: 'Your appointment', note: 'Forty minutes as standard, with the clinician you chose.' },
    { title: 'Follow-up', note: 'A review within fourteen days, included in the fee.' },
  ],
  proof: [
    { value: '2,400+', label: 'Appointments' },
    { value: '14 yrs', label: 'Experience' },
  ],

  assistant: {
    greeting: "Good day — I'm Saint, the concierge for Teduh Clinic.",
    offer: 'I can book you in, move an appointment, or answer anything about the clinic.',
    nudgeTitle: 'Need a slot this week?',
    nudgeBody: 'I can check the diary and book you in — it takes about thirty seconds.',
    human: 'Marguerite Vance',
    humanRole: 'Patient coordinator',
  },

  skills: { order: false, reserve: false, appointment: true },
  itemNoun: 'treatment',
  itemNounPlural: 'treatments',
  tagNoun: 'Includes',
  peopleNoun: 'clinicians',

  categories: [
    { id: 'general', name: 'General medicine', note: 'Whole-picture consultations' },
    { id: 'derm', name: 'Dermatology', note: 'Skin, hair and nails' },
    { id: 'dental', name: 'Dental', note: 'Hygiene and restorative' },
    { id: 'physio', name: 'Physiotherapy', note: 'Movement and recovery' },
  ],

  catalog: [
    {
      id: 'a1',
      name: 'General consultation',
      categoryId: 'general',
      price: 120,
      description:
        'A full forty minutes with one of our physicians, including examination and a written plan.',
      tags: ['Written plan', 'Referrals'],
      duration: '40 min',
      available: true,
      hue: 168,
      popular: true,
      sold: 186,
    },
    {
      id: 'a2',
      name: 'Annual health review',
      categoryId: 'general',
      price: 480,
      description: 'Bloods, ECG, lung function and a ninety-minute review of the results with you.',
      tags: ['Bloods', 'ECG', '90 min'],
      duration: '90 min',
      available: true,
      hue: 186,
      sold: 64,
    },
    {
      id: 'a3',
      name: 'Mole mapping & skin check',
      categoryId: 'derm',
      price: 180,
      description:
        'Full-body dermoscopy, photographed and compared against your previous visit.',
      tags: ['Photography', 'Report'],
      duration: '45 min',
      available: true,
      hue: 24,
      popular: true,
      sold: 142,
    },
    {
      id: 'a4',
      name: 'Acne & rosacea consultation',
      categoryId: 'derm',
      price: 165,
      description: 'Assessment, a prescription where appropriate, and a six-week follow-up included.',
      tags: ['Prescription', 'Follow-up'],
      duration: '40 min',
      available: true,
      hue: 8,
      sold: 98,
    },
    {
      id: 'a5',
      name: 'Hygiene & six-month check',
      categoryId: 'dental',
      price: 95,
      description: 'Scale, polish, and a full examination with small X-rays if they are due.',
      tags: ['X-rays', 'Polish'],
      duration: '40 min',
      available: true,
      hue: 200,
      sold: 224,
    },
    {
      id: 'a6',
      name: 'Composite bonding',
      categoryId: 'dental',
      price: 340,
      description: 'Per tooth, shade-matched and finished in a single visit.',
      tags: ['Single visit'],
      duration: '60 min',
      available: false,
      hue: 46,
      sold: 37,
    },
    {
      id: 'a7',
      name: 'Physiotherapy session',
      categoryId: 'physio',
      price: 110,
      description: 'Movement assessment, hands-on treatment, and exercises you will actually do.',
      tags: ['Hands-on', 'Home plan'],
      duration: '50 min',
      available: true,
      hue: 148,
      popular: true,
      sold: 176,
    },
    {
      id: 'a8',
      name: 'Running gait analysis',
      categoryId: 'physio',
      price: 145,
      description: 'Treadmill filming from four angles, with a written report and load plan.',
      tags: ['Video', 'Report'],
      duration: '60 min',
      available: true,
      hue: 210,
      sold: 52,
    },
  ],

  people: [
    {
      id: 'p1',
      name: 'Amara Okonjo',
      title: 'Dr',
      role: 'General medicine',
      focus: ['general', 'derm'],
      rating: 4.9,
      reviews: 218,
      next: 'Today, 15:30',
      hue: 168,
      bio: 'Fifteen years in general practice, with an interest in long-term fatigue.',
    },
    {
      id: 'p2',
      name: 'Levi Hartmann',
      title: 'Dr',
      role: 'Dermatology',
      focus: ['derm', 'general'],
      rating: 4.8,
      reviews: 164,
      next: 'Tomorrow, 09:00',
      hue: 24,
      bio: 'Consultant dermatologist, mole mapping and skin cancer surveillance.',
    },
    {
      id: 'p3',
      name: 'Noor Rahimi',
      title: 'Dr',
      role: 'Dental surgery',
      focus: ['dental'],
      rating: 5,
      reviews: 91,
      next: 'Today, 17:00',
      hue: 200,
      bio: 'Restorative and cosmetic dentistry, unhurried and unusually gentle.',
    },
    {
      id: 'p4',
      name: 'Sena Ellery',
      title: 'Ms',
      role: 'Physiotherapy',
      focus: ['physio'],
      rating: 4.9,
      reviews: 143,
      next: 'Thu, 11:15',
      hue: 148,
      bio: 'Musculoskeletal physiotherapist, works with three London running clubs.',
    },
  ],

  hours: [
    { day: 'Monday – Thursday', hours: '08:00 – 19:00' },
    { day: 'Friday', hours: '08:00 – 17:30' },
    { day: 'Saturday', hours: '09:00 – 14:00' },
    { day: 'Sunday', hours: 'Closed' },
  ],

  faq: [
    {
      id: 'f1',
      q: 'Which insurers do you accept?',
      a: 'We bill Bupa, AXA Health, Vitality and Aviva directly. Cigna and WPA we invoice, and you claim it back.',
      source: 'Insurance & billing',
      category: 'Billing',
      uses: 231,
      confidence: 98,
      updated: '4 days ago',
      status: 'live',
    },
    {
      id: 'f2',
      q: 'Do I need a referral?',
      a: 'Not for anything on our list. If your insurer needs one, your GP can send it straight to us.',
      source: 'Before your visit',
      category: 'Appointments',
      uses: 178,
      confidence: 96,
      updated: '1 week ago',
      status: 'live',
    },
    {
      id: 'f3',
      q: 'What is your cancellation policy?',
      a: 'Free up to 24 hours before. Inside 24 hours we charge half the fee, waived if you are unwell.',
      source: 'Cancellation policy',
      category: 'Policies',
      uses: 142,
      confidence: 99,
      updated: 'Yesterday',
      status: 'live',
    },
    {
      id: 'f4',
      q: 'Is the clinic step-free?',
      a: 'Yes. The Marlowe Street entrance is level, the lift reaches every floor, and blue-badge bays sit outside.',
      source: 'Access & parking',
      category: 'Visiting',
      uses: 97,
      confidence: 93,
      updated: '2 weeks ago',
      status: 'live',
    },
    {
      id: 'f5',
      q: 'Can I get a repeat prescription?',
      a: 'If we prescribed it in the last six months, yes — usually the same working day.',
      source: 'Prescriptions',
      category: 'Treatments',
      uses: 64,
      confidence: 74,
      updated: '6 hours ago',
      status: 'draft',
    },
    {
      id: 'f6',
      q: 'Do you see children?',
      a: 'From twelve upwards for dermatology and physiotherapy. Under twelve we refer to the Portland.',
      source: 'Who we treat',
      category: 'Appointments',
      uses: 38,
      confidence: 86,
      updated: '3 weeks ago',
      status: 'review',
    },
  ],
};

const solene: Brand = {
  id: 'solene',
  vertical: 'salon',
  name: 'Rona',
  legal: 'Rona Studio',
  kind: 'Hair studio · Shoreditch',
  scheme: 'light',
  currency: '£',
  address: '4 Redchurch Street, Shoreditch',
  district: 'London E2',
  phone: '+44 20 7946 0533',

  hero: {
    eyebrow: 'Colour specialists · Shoreditch',
    line1: 'Hair that grows',
    line2: 'out beautifully.',
    body: 'Cut for how it falls in six weeks, not just how it looks at the door. Colour by people who have been doing it for a decade.',
    cta: 'Book a chair',
    stats: [
      { value: '4.9', label: 'From 860 reviews' },
      { value: '6', label: 'Stylists' },
      { value: '10', label: 'Years open' },
    ],
  },
  nav: ['Services', 'Stylists', 'Retail', 'Journal'],

  images: {
    hero: 'photo-1633681926022-84c23e8cb2d6',
    feature: [
      'photo-1595475884562-073c30d45670',
      'photo-1521590832167-7bcbfaa6381f',
      'photo-1589729132389-8f0e0b55b91e',
    ],
    story: 'photo-1521590832167-7bcbfaa6381f',
  },
  story: {
    eyebrow: 'The studio',
    title: 'Cut for week six, not for the walk to the door.',
    body: 'Six stylists on Redchurch Street who have been doing this for a decade. Consultation first, always, and we will say no if it will not work.',
    points: [
      'Every colour starts with a patch test, 48 hours before',
      'Bond repair included on all lightening work',
      'Retail ships next day, free over fifty pounds',
    ],
  },
  marquee: ['Colour specialists', 'Cut & finish', 'Bond repair', 'Retail', 'Shoreditch'],
  process: [
    { title: 'Consultation first', note: 'We look at your hair, not a photograph on a phone.' },
    { title: 'Patch test', note: 'Forty-eight hours before any colour. Two minutes, no charge.' },
    { title: 'In the chair', note: 'Cut and colour built around how it grows, not how it sits today.' },
    { title: 'Growing it out', note: 'A plan for week six, and the products to hold it there.' },
  ],
  proof: [
    { value: '860+', label: 'Reviews' },
    { value: '10 yrs', label: 'On Redchurch St' },
  ],

  assistant: {
    greeting: "Hello — I'm Saint, front desk at Rona.",
    offer: 'I can book you a chair, match you to a stylist, or send products to your door.',
    nudgeTitle: 'Roots showing?',
    nudgeBody: 'Two cancellations opened up this week. Want me to hold one for you?',
    human: 'Iris Bellamy',
    humanRole: 'Studio manager',
  },

  skills: { order: true, reserve: false, appointment: true },
  itemNoun: 'service',
  itemNounPlural: 'services',
  tagNoun: 'Includes',
  peopleNoun: 'stylists',

  categories: [
    { id: 'cut', name: 'Cut & finish', note: 'Consultation always included' },
    { id: 'colour', name: 'Colour', note: 'Patch test 48 hours before' },
    { id: 'care', name: 'Treatments', note: 'Add to any appointment' },
    { id: 'retail', name: 'Retail', note: 'Delivered next day' },
  ],

  catalog: [
    {
      id: 's1',
      name: 'Cut & blow dry',
      categoryId: 'cut',
      price: 85,
      description: 'A proper consultation, a cut built around your growth pattern, finished dry.',
      tags: ['Consultation', 'Finish'],
      duration: '60 min',
      available: true,
      hue: 330,
      popular: true,
      sold: 318,
    },
    {
      id: 's2',
      name: 'Restyle',
      categoryId: 'cut',
      price: 120,
      description: 'Ninety minutes for a real change, with photographs and a plan for growing it out.',
      tags: ['90 min', 'Plan'],
      duration: '90 min',
      available: true,
      hue: 312,
      sold: 94,
    },
    {
      id: 's3',
      name: 'Full head highlights',
      categoryId: 'colour',
      price: 210,
      description: 'Hand-painted foils through the whole head, toned and finished. Allow three hours.',
      tags: ['Patch test', 'Toner', '3 hr'],
      duration: '180 min',
      available: true,
      hue: 44,
      popular: true,
      sold: 176,
    },
    {
      id: 's4',
      name: 'Root tint & gloss',
      categoryId: 'colour',
      price: 95,
      description: 'Regrowth covered and a gloss through the lengths to bring the tone back.',
      tags: ['Patch test', 'Gloss'],
      duration: '75 min',
      available: true,
      hue: 20,
      sold: 262,
    },
    {
      id: 's5',
      name: 'Balayage',
      categoryId: 'colour',
      price: 245,
      description: 'Freehand lightening for a soft grow-out, toned to the tone you actually asked for.',
      tags: ['Patch test', '3 hr'],
      duration: '180 min',
      available: false,
      hue: 36,
      sold: 131,
    },
    {
      id: 's6',
      name: 'Bond repair treatment',
      categoryId: 'care',
      price: 45,
      description: 'Twenty minutes under heat, rebuilding the bonds colour work takes out.',
      tags: ['20 min', 'Add-on'],
      duration: '20 min',
      available: true,
      hue: 288,
      sold: 208,
    },
    {
      id: 's7',
      name: 'Scalp ritual',
      categoryId: 'care',
      price: 38,
      description: 'Exfoliation, a long massage, and a light oil. Booked as an add-on or on its own.',
      tags: ['30 min', 'Massage'],
      duration: '30 min',
      available: true,
      hue: 156,
      sold: 141,
    },
    {
      id: 's8',
      name: 'Rona Repair Mask 200ml',
      categoryId: 'retail',
      price: 34,
      description: 'The mask we use in the basin, in a jar. Once a week, ten minutes, that is all.',
      tags: ['Vegan', '200 ml'],
      available: true,
      hue: 300,
      popular: true,
      sold: 386,
    },
    {
      id: 's9',
      name: 'Everyday Shampoo 300ml',
      categoryId: 'retail',
      price: 26,
      description: 'Sulphate-free, colour-safe, and it lathers properly — which most of them do not.',
      tags: ['Vegan', '300 ml'],
      available: true,
      hue: 190,
      sold: 421,
    },
    {
      id: 's10',
      name: 'Finishing Oil 50ml',
      categoryId: 'retail',
      price: 29,
      description: 'Two drops through the ends. Weightless, and it does not smell of coconut.',
      tags: ['50 ml'],
      available: true,
      hue: 40,
      sold: 254,
    },
  ],

  people: [
    {
      id: 'p1',
      name: 'Noa Bright',
      title: '',
      role: 'Creative director',
      focus: ['cut', 'colour'],
      rating: 5,
      reviews: 312,
      next: 'Fri, 10:00',
      hue: 330,
      bio: 'Twelve years cutting, six of them teaching. Books up about three weeks out.',
    },
    {
      id: 'p2',
      name: 'Malik Osei',
      title: '',
      role: 'Senior colourist',
      focus: ['colour', 'care'],
      rating: 4.9,
      reviews: 204,
      next: 'Today, 16:00',
      hue: 44,
      bio: 'Balayage and corrective colour. Unusually good with dark hair going lighter.',
    },
    {
      id: 'p3',
      name: 'Wren Tolliver',
      title: '',
      role: 'Stylist',
      focus: ['cut', 'care'],
      rating: 4.8,
      reviews: 118,
      next: 'Today, 12:30',
      hue: 288,
      bio: 'Curls, fringes and short cuts. Trained under Noa for four years.',
    },
    {
      id: 'p4',
      name: 'Elif Kaya',
      title: '',
      role: 'Colourist',
      focus: ['colour'],
      rating: 4.9,
      reviews: 96,
      next: 'Tomorrow, 09:30',
      hue: 20,
      bio: 'Tonal work and grey blending, with a very light touch on the scissors.',
    },
  ],

  hours: [
    { day: 'Tuesday – Friday', hours: '09:00 – 20:00' },
    { day: 'Saturday', hours: '09:00 – 18:00' },
    { day: 'Sunday', hours: '11:00 – 17:00' },
    { day: 'Monday', hours: 'Closed' },
  ],

  faq: [
    {
      id: 'f1',
      q: 'Do I need a patch test?',
      a: 'For any colour, yes — 48 hours before, and it takes two minutes. I can post you one or you can drop in.',
      source: 'Colour safety',
      category: 'Colour',
      uses: 268,
      confidence: 99,
      updated: '3 days ago',
      status: 'live',
    },
    {
      id: 'f2',
      q: 'How much is balayage?',
      a: 'From £245 with a senior colourist, including toner and finish. Long or very dark hair may need a second session.',
      source: 'Price list',
      category: 'Pricing',
      uses: 197,
      confidence: 95,
      updated: '1 week ago',
      status: 'live',
    },
    {
      id: 'f3',
      q: 'What if I need to cancel?',
      a: 'Free up to 48 hours before. Inside that we ask for 50%, because the chair usually goes empty.',
      source: 'Cancellation policy',
      category: 'Policies',
      uses: 134,
      confidence: 98,
      updated: '2 weeks ago',
      status: 'live',
    },
    {
      id: 'f4',
      q: 'Do you do hair extensions?',
      a: 'Tape and micro-ring, by consultation only. Noa and Elif fit them; allow two hours.',
      source: 'Extensions',
      category: 'Services',
      uses: 88,
      confidence: 87,
      updated: '1 month ago',
      status: 'live',
    },
    {
      id: 'f5',
      q: 'Can I buy products online?',
      a: 'Yes — everything on the retail shelf ships next day, free over £50.',
      source: 'Retail & delivery',
      category: 'Retail',
      uses: 71,
      confidence: 91,
      updated: '5 days ago',
      status: 'live',
    },
    {
      id: 'f6',
      q: 'Is there a student discount?',
      a: '20% off cuts on Tuesdays and Wednesdays with a valid card, excluding colour.',
      source: 'Offers',
      category: 'Pricing',
      uses: 44,
      confidence: 79,
      updated: '2 months ago',
      status: 'review',
    },
  ],
};

export const BRANDS: Record<BrandId, Brand> = { lumiere, aurelia, solene };
export const BRAND_ORDER: BrandId[] = ['lumiere', 'aurelia', 'solene'];
